# Final-Project

**Note to Dr. Z:** 

Right at the finish line, when almost everything was working correctly, we attempted to change a field in the dable and the following error was thrown: `relation ____ already exists`. We’ve tried flushing the database, faking migrations, and looking up every line of the error– and as far as we could find in the limitted time we had, no common solutions work. All we were trying to do was make some edits to the table! Django is extremely frustrating sometimes. We have a screenrecording from when it was working properly that we can email to you if you would like.

**Instructions**

To run a simulation of the Course Requests app:
1. Clone this GitHub repository
2. Open the Frontend Folder
3. Open `MyCourseRequests.xcodeproj`
4. Set `GLOBAL.HAS_LOADED` flag to `false` in `GLOBAL.swift`
5. Click the play button in the top left corner to run the simulator
6. Set `GLOBAL.HAS_LOADED` flag to `true` in `GLOBAL.swift`
7. Rerun the application by clicking the play button in the top left corner to run the simulator again

[Future To-Do List](https://docs.google.com/document/d/1gRt1i636co1LcXHaMP7cacLdP8MdHRPC_Sd443cGAjk/edit?usp=sharing)

[Security Audit](https://docs.google.com/document/d/1g9xzPsCy1hREPQt87PbeCfpdGBbvR67zIUyOzyeQNNU/edit?usp=sharing)
